### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/react-components#14]
In order for everyone to spend less time reviewing and fixing PRs, the readme should be more clear about how to get a PR approved. We should agree on some guidelines.

I think the following should be required:

1. Adding a component readme (and demo for complex components)
2. Removing as much of project specific component API as possible (generalizing)

I think we should discuss these:

3. Do we want components that use new patterns and ideas (like themes, render props, context) as tools of demonstration in cases where this isn't strictly necessary? For context, this was discussed [here](https://github.com/Creuna-Oslo/react-components/pull/6#discussion_r199779296)
4. Should css be limited to the bare essentials?
5. Adding a link to component in main readme (or drop these links alltogether)

**Comment by asbjornh** [comment]
My thoughts:

3. and 4. : I think that keeping components as lean and simple as possible increases their ease of use. When a component has stuff that you have to delete every time you import it, this becomes a chore. This is especially true of css, which in nearly every case has to be completely replaced.

5. : I think we should remove them at some point. It's nice to have big links on the front page of the repo to go directly to a component but I think in the long run this might be a hassle to maintain

**Comment by allermand** [comment]
It hurts my eyes that some components use BEM naming for css classes and others don't. Guess we need (a minimum of) css for adding classes like `.list--inline` (props) and `.list__item` (children) to components, but I'd prefer a unified naming standard for all components.
